[project]
name = "bin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2025.6.15",
    "charset-normalizer>=3.4.2",
    "idna>=3.10",
    "pytest>=8.4.0",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "scrapetube>=2.5.1",
    "typing-extensions>=4.14.0",
    "urllib3>=2.4.0",
    "uvloop>=0.21.0",
    "youtube-transcript-api>=1.1.0",
]
