[project]
name = "yt_bulk_cc"
version = "1.0.0"
description = "Bulk download YouTube transcripts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2025.6.15",
    "charset-normalizer>=3.4.2",
    "idna>=3.10",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "scrapetube>=2.5.1",
    "typing-extensions>=4.14.0",
    "urllib3>=2.4.0",
    "uvloop>=0.21.0",
    "youtube-transcript-api==1.1.1",
]

[project.scripts]
yt-bulk-cc = "yt_bulk_cc.cli:cli_entry"

[build-system]
requires = ["uv", "setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
