[project]
name            = "site_downloader"
version         = "0.0.1"
description     = "Unified CLI to fetch pages, clean HTML, convert, and render PDFs/PNGs via Playwright."
requires-python = ">=3.10"

dependencies = [
  "typer>=0.12",
  "playwright>=1.44",
  "html2text>=2020.1.16",
  "tqdm>=4.66",
  "pydantic>=2.7",
  "readability-lxml>=0.8",
  "user-agents>=2.2",
  "beautifulsoup4>=4.12",
  "markdownify>=0.11",
  "markitdown>=0.1.2",
  "fake-useragent>=2.2",
  "fake-headers>=1.0",
  "aiofiles>=24.1.0",
  "swiftshadow>=2.2",
  "requests[socks]>=2.32.4",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
sdl = "site_downloader.cli:app"      # `sdl --help`

[build-system]
requires = ["uv", "setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
